---
AllCops:
  Exclude:
    - 'trees/**/*'
    - 'vendor/**/*'

Layout/ClosingHeredocIndentation:
  Exclude:
    - 'Vagrantfile'

Layout/ExtraSpacing:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'Vagrantfile'
    - 'test/tree_planter_test.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Exclude:
    - 'Vagrantfile'

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

