---
version: 1

update_configs:
  - package_manager: 'ruby:bundler'
    directory: '/'
    update_schedule: 'daily'
    target_branch: 'develop'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
  - package_manager: 'docker'
    directory: '/'
    update_schedule: 'daily'
    target_branch: 'develop'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'

