name: Docker Image CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Test Locally
        env:
          WORKSPACE: ${{ github.workspace }}
        run: |
          echo 'Creating config.json and trees dir for testing'
          echo "id -u $USER"
          printf "{ \"base_dir\": \"${WORKSPACE}/trees\" }" > ${WORKSPACE}/config.json
          mkdir ${{ github.workspace }}/trees
          echo 'Testing app code outside of Docker...'
          bundle exec rake test || exit 1
          bundle exec rake rubocop || exit 1

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: ${{ github.repository }}:${{ github.sha }}

      - name: Test Docker Image
        env:
          WORKSPACE: ${{ github.workspace }}
          REPOSITORY: ${{ github.repository }}
          GIT_REF: ${{ github.ref }}
        run: |
          docker run -d -p 127.0.0.1:80:8080 --name planted_trees -v ${{ github.workspace }}/trees:/opt/trees -e LOCAL_USER_ID=`id -u $USER` ${{ github.repository }}:${{ github.sha }}
          docker ps -a
          docker exec planted_trees /bin/sh -c 'bundle exec rake test'
          docker exec planted_trees /bin/sh -c 'bundle exec rake rubocop'
          echo "Removing all files from ${WORKSPACE}/trees/"
          sudo rm -rf ${{ github.workspace }}/trees/*
          bash test/ci_test_running_container.sh
